name: Block Direct Push
on:
  push:
    branches: [main, develop]

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct push
        run: |
          echo "Error: Direct pushing to 'main' or 'develop' branches is not allowed. Use pull requests."
          exit 1